name: GuardianKitPvP
version: ${project.version}
main: dev.mruniverse.guardiankitpvp.GuardianKitPvP
api-version: 1.16
depend: [ GuardianLIB ]
authors: [ MrUniverse44 ]
description: Simple KitPvP Plugin
commands:
  gkp:
    description: Main command of the plugin
  kp:
    description: Main command of the plugin