# # # # # # # # # # # # # # # # # # # # # #
#           Made by Wazup92               #
#     If you really like the plugin       #
#     Then please dont forget to leave    #
#        A positive 5 stars review!       #
# # # # # # # # # # # # # # # # # # # # # #

use-UUID: false
Map-Load-Delay: 10
Starting-Coins: 1000
Check-For-Updates: true
Scoreboard-Enabled: true
Notify-When-Cooldown-Off: true
Kill-Coins-Contribution: true
Do-Players-Drop-Items-On-Death: false
Can-Players-Drop-Items-On-Ground: false
Can-Players-Pick-Items-On-Ground: false
Do-Players-Lose-Hunger: false
Purchaseable-Kits-Are-Permanent: true
Show-Health-Below-Name: true
Starting-Amount-Of-Kit-Unlockers: 2
Respawn-Screen-On-Death: false
Spawn-Teleport-Countdown-Seconds: 5
Spectate-Countdown-Seconds: 5
Earned-Coins-Per-Kill: 8
Minimum-Exp-Per-Kill: 2
Maximum-Exp-Per-Kill: 5
Sponge-Boost-Upwards: 1.5
Update-Leaderboard-Every-Minutes: 60
Sell-Value: 0.33
Challenge-Lives: 2
Challenge-Respawn-Protection-Seconds: 5
Minimum-Bounty: 25
Soup-Auto-Disappear: false
Fall-Damage-Enabled: true
Open-Kits-Menu-On-Respawn: false
Broadcast-Rank-Up: true
Show-Rank-In-Chat: true
Send-Death-Message-To-Everyone: true
Allow-Building: false
Soup-Drop-Sound: true
Sponge-Launch-Sound: true
Void-Instant-Death: true
Leave-Command-Timer: 3
Default-Kits:
  - Pvp
Send-Killstreaks-To-Everyone: true
Killstreaks-Enabled: true
Deathstreaks-Enabled: true
use-Vault: false

Saving-Task:
  Enabled: true
  Save-Every-Minutes: 10

use-mysql: false
table-prefix: kitbattle_
mysql-host: localhost
mysql-port: 3306
mysql-database: database
mysql-username: root
mysql-password: root

Bungee-Mode: false
Shuffle-Every-In-Minutes: 30
Time-Shown-Before-Shuffle: [60, 30, 15, 10, 5, 4, 3, 2, 1]

Kit-Lores:
  Owned: [' ', '&d&lState: %statecolor%%state%', '&d&lRequires Permission: %permissioncolor%%requirespermission%', ' ', '&d- &b&nLeft click to equip &d/ &c&nRight click to sell']
  Shop: [' ', '&d&lState: %statecolor%%state%', '&d&lRequires Permission: %permissioncolor%%requirespermission%', ' ', '&c&nRight click to preview this kit!', ' ', '&6&lPrice: &e%price% &6coins!']

Tournaments:
  min-players: 7
  grace-period: 15
  countdown-length: 30
  max-time: 600
  celebration-length: 12
  fireworks-celebration: true
  winner-rewards:
    - 'kb coins add %winner% 100'
    - 'kb kitunlocker give %winner% 1'
  time-shown-during-countdown: [30, 15, 10, 5, 4, 3, 2, 1]
  grace-period-warnings: [15, 10, 5, 4, 3, 2, 1]
  end-warnings: [60, 30, 15, 10, 5, 4, 3, 2, 1]

Challenges:
  grace-length: 15
  max-time: 300
  celebration-length: 12
  fireworks-celebration: true
  winner-rewards:
    - 'kb coins add %winner% 50'
  grace-period-warnings: [15, 10, 5, 4, 3, 2, 1]
  end-warnings: [60, 30, 15, 10, 5, 4, 3, 2, 1]
  kit-lock:
    enabled: false
    challenge-kit: Pvp

Create-Default-Kits: true

Aliases:
  - kitpvp
  - pvp
Allowed-Commands:
  - kb
  - kitbattle
  - tell
  - help
  - t
  - r

Items:
  Kit-Selector: 'CHEST : &7Kit Selector (&aRight click!&7)'
  Shop-Opener: 'ANVIL : &7Shop (&aRight click!&7)'
  Challenges-Item: 'BLAZE_ROD : &6Challenges'
  Profile-Item: 'PAPER : &aStats'
  Kit-Unlocker: 'CHEST : &7Kit Unlocker! (&aRight click!&7)'
  Trails-Opener: 'ENCHANTED_BOOK : &eTrails &6[VIP]'

Modifiers: ['2 : kitbattle.vip', '3 : kitbattle.ultravip']

Trails:
  enabled: true
  size: 2
  interval: 3

Action-Bar:
  enabled: true
  Ability-Cooldown:
    enabled: false
    update-speed: 11
    time-format: '0.0'
Titles:
  enabled: true
  fadeIn: 10
  stay: 40
  fadeOut: 10

Scoreboard-Title-Animation:
  enabled: false
  interval: 8
  frames: ['&b&l&nKitBattle', '&e&l&nKitBattle', '&b&l&nKitBattle', '&a&l&nKitBattle', '&b&l&nKitBattle', '&c&l&nKitBattle', '&e&l&nK&b&l&nitBattle', '&b&l&nK&e&l&ni&b&l&ntBattle', '&b&l&nKi&e&l&nt&b&l&nBattle', '&b&l&nKit&e&l&nB&b&l&nattle', '&b&l&nKitB&e&l&na&b&l&nttle', '&b&l&nKitBa&e&l&nt&b&l&ntle', '&b&l&nKitBat&e&l&nt&b&l&nle', '&b&l&nKitBatt&e&l&nl&b&l&ne', '&b&l&nKitBattl&e&l&ne']

Deathstreak-End-Commands: ['effect %player% resistance 1 2', 'effect %player% regeneration 1 2', 'effect %player% strength 1 1', 'effect %player% speed 1 1']