#   _____                     _ _               _  ___ _   _____        _____
#  / ____|                   | (_)             | |/ (_) | |  __ \      |  __ \
# | |  __ _   _  __ _ _ __ __| |_  __ _ _ __   | ' / _| |_| |__) |_   _| |__) |
# | | |_ | | | |/ _` | '__/ _` | |/ _` | '_ \  |  < | | __|  ___/\ \ / /  ___/
# | |__| | |_| | (_| | | | (_| | | (_| | | | | | . \| | |_| |     \ V /| |
#  \_____|\__,_|\__,_|_|  \__,_|_|\__,_|_| |_| |_|\_\_|\__|_|      \_/ |_|
#
# Created by: MrUniverse44
# SpigotMC Link: N/A
#
settings:
  # Plugin Date Format
  dateFormat: "dd/MM/yyyy"
  # Toggle perWorldTab option
  perWorldTab: false
  # Map Locations:
  map-locations: []
  # Progress Bar Custom
  progressBar:
    left: '&8&l► '
    unicode: '▌'
    right: ' &8&l◀'
    color-complete: '&a'
    color-pending: '&7'
  # Chat System
  chat:
    # Toggle this option
    toggle: true
    # Format (Support PlaceholderAPI)
    format: '%rank_prefix%&7%player% &8» &7%message%.'
  # Leave Cancel Time (In Seconds)
  leaveCancelTime: 3
  # Toggle Update Check
  update-check: true
  # Game Settings
  game:
    use-uuid-on-data: false
    starting-coins: 1000
    starting-kits-unlockers: 2
    allow-drop-items-on-ground: false
    allow-pick-items-on-ground: false
    allow-fall-damage: false
    allow-hunger: false
    broadcast-level-up: false
    respawn-delay:
      toggle: false
      delay: 5
    bounty:
      min-value-to-bounty: 250
      max-value-to-bounty: 10000
    default-kits:
      # Toggle
      toggle: true
      # Kit ID (For this, you need use only KitID's, by default: 0)
      default: 0
  # Save Task Settings
  saving-Task:
    toggle: true
    value-in-minutes: 10
  # MySQL Settings
  mysql:
    toggle: false
    jdbc-url: 'jdbc:mysql://[host]:[port]/[db]?autoReconnect=true'
    table-prefix: 'guardiankitpvp_'
    host: 'localhost'
    port: '3306'
    database: 'database'
    username: 'root'
    password: 'root'
  # Tournament Settings
  tournaments:
    min-players: 7
    grace-period: 15
    countdown-length: 30
    max-time: 600
    fireworks-celebration: true
    winner-rewards:
      - 'kpvp admin give coins %winner% 100'
      - 'kpvp admin give kitunlocker %winner% 1'
  # In-Game Command Settings
  allowed-Commands:
    - kpvp
    - kitpvp
    - gkpvp
    - guardiankitpvp
    - tell
    - help
    - t
    - r


  titles:
    enabled: true
    fadeIn: 10
    stay: 40
    fadeOut: 10